"""empty message

Revision ID: 147e582d05ca
Revises: 3f3495308876
Create Date: 2017-10-17 10:37:02.281535

"""

# revision identifiers, used by Alembic.
revision = '147e582d05ca'
down_revision = '3f3495308876'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
