"""empty message

Revision ID: 46137a7876b4
Revises: 524d612b43c8
Create Date: 2017-10-17 14:16:05.860271

"""

# revision identifiers, used by Alembic.
revision = '46137a7876b4'
down_revision = '524d612b43c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
