"""empty message

Revision ID: 524d612b43c8
Revises: 147e582d05ca
Create Date: 2017-10-17 14:14:13.243439

"""

# revision identifiers, used by Alembic.
revision = '524d612b43c8'
down_revision = '147e582d05ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
